import Foundation

// MARK: - AppLanguage

enum AppLanguage: String, CaseIterable, Codable {
    case en, tr, es, de, fr, zh, ja, ru, ko

    var displayName: String {
        switch self {
        case .en: return "English"
        case .tr: return "Türkçe"
        case .es: return "Español"
        case .de: return "Deutsch"
        case .fr: return "Français"
        case .zh: return "中文"
        case .ja: return "日本語"
        case .ru: return "Русский"
        case .ko: return "한국어"
        }
    }

    /// Maps first preferred system language to AppLanguage; falls back to .en.
    static func systemDefault() -> AppLanguage {
        guard let code = Locale.preferredLanguages.first else { return .en }
        let prefix = String(code.prefix(2)).lowercased()
        return AppLanguage(rawValue: prefix) ?? .en
    }
}

// MARK: - L() — global localisation function

/// Returns the localised string for `key` in the current language.
/// Falls back to `key` itself (which is the English string).
func L(_ key: String) -> String {
    let lang = Store.shared.language
    if lang == .en { return key }
    return translations[lang]?[key] ?? key
}

// MARK: - Translation table

private let translations: [AppLanguage: [String: String]] = [

    .tr: [
        // General / nav
        "Items":            "Öğeler",
        "Context":          "Bağlam",
        "General":          "Genel",
        "Settings…":        "Ayarlar…",
        "Orbit Settings":   "Orbit Ayarları",
        "Orbit Launcher":   "Orbit Başlatıcı",
        "Quit Orbit":       "Orbit'ten Çık",
        "Language":         "Dil",

        // Breadcrumb / items tab
        "Radial Items":     "Radyal Öğeler",
        "Add App…":         "Uygulama Ekle…",
        "Add File or Folder…": "Dosya veya Klasör Ekle…",
        "Add Link…":        "Bağlantı Ekle…",
        "Add System Action":"Sistem Eylemi Ekle",
        "Add Shortcut…":    "Kısayol Ekle…",
        "Add Script…":      "Betik Ekle…",
        "Add Folder…":      "Klasör Ekle…",
        "Add":              "Ekle",
        "Cancel":           "İptal",
        "Create":           "Oluştur",

        // Empty states
        "No items yet":     "Henüz öğe yok",
        "No items":         "Öğe yok",
        "Use the + button to add items.": "Öğe eklemek için + düğmesine bas.",
        "Use the + button or drag files here.": "Öğe eklemek için + düğmesine bas veya dosyaları buraya sürükle.",
        "Folder is empty":  "Klasör boş",
        "Release to add files": "Dosya eklemek için bırak",

        // App picker
        "Search apps…":     "Uygulama ara…",
        "Scanning apps…":   "Uygulamalar taranıyor…",
        "selected":         "seçildi",

        // Shortcut picker
        "Search shortcuts…":"Kısayol ara…",
        "Loading shortcuts…":"Kısayollar yükleniyor…",
        "No shortcuts found":"Kısayol bulunamadı",

        // Overlays
        "New Folder":       "Yeni Klasör",
        "Folder name":      "Klasör adı",
        "Add Link":         "Bağlantı Ekle",
        "Title (optional)": "Başlık (isteğe bağlı)",
        "Title":            "Başlık",
        "URL":              "URL",
        "Add Shell Script": "Kabuk Betiği Ekle",
        "Script name":      "Betik adı",
        "Script":           "Betik",
        "Shell script":     "Kabuk betiği",

        // Type labels
        "App":              "Uygulama",
        "File":             "Dosya",
        "Link":             "Bağlantı",
        "System":           "Sistem",
        "Shortcut":         "Kısayol",
        "Folder":           "Klasör",
        "Clipboard":        "Pano",

        // System actions
        "Sleep":            "Uyku",
        "Lock Screen":      "Ekranı Kilitle",
        "Screen Saver":     "Ekran Koruyucu",
        "Empty Trash":      "Çöpü Boşalt",
        "Screenshot":       "Ekran Görüntüsü",

        // Context tab
        "Context Sets":     "Bağlam Setleri",
        "App:":             "Uygulama:",
        "Choose…":          "Seç…",
        "No items for this app": "Bu uygulama için öğe yok",
        "Use the + button to add items to this context set.": "Bu bağlam setine öğe eklemek için + düğmesine bas.",
        "Select an app above to create a custom item set\nthat appears when that app is in front.":
            "Öndeki uygulamaya özel öğe seti oluşturmak için\nyukarıdan bir uygulama seç.",

        // General tab
        "Startup":          "Başlangıç",
        "Start at Login":   "Girişte Başlat",
        "Trigger":          "Tetikleyici",
        "Mouse shake (hold ⌥ + shake)": "Fare sallama (⌥ basılı tut + salla)",
        "Sensitivity":      "Hassasiyet",
        "Keyboard Shortcut":"Klavye Kısayolu",
        "Toggle radial menu":"Radyal menüyü aç/kapat",

        // Accessibility alert
        "Accessibility Permission Required": "Erişilebilirlik İzni Gerekli",
        "Orbit needs Accessibility access to detect mouse shake while Option is held.\n\nEnable it in System Settings → Privacy & Security → Accessibility, then relaunch Orbit.":
            "Orbit, ⌥ tuşu basılıyken fare sallamasını algılamak için Erişilebilirlik iznine ihtiyaç duyar.\n\nSistem Ayarları → Gizlilik ve Güvenlik → Erişilebilirlik bölümünden etkinleştir, ardından Orbit'i yeniden başlat.",
        "Open System Settings": "Sistem Ayarlarını Aç",
        "Later":            "Sonra",
        "Open Settings to add items": "Öğe eklemek için Ayarlar'ı aç",
    ],

    .es: [
        "Items":            "Elementos",
        "Context":          "Contexto",
        "General":          "General",
        "Settings…":        "Ajustes…",
        "Orbit Settings":   "Ajustes de Orbit",
        "Orbit Launcher":   "Orbit Launcher",
        "Quit Orbit":       "Salir de Orbit",
        "Language":         "Idioma",
        "Radial Items":     "Elementos Radiales",
        "Add App…":         "Añadir app…",
        "Add File or Folder…": "Añadir archivo o carpeta…",
        "Add Link…":        "Añadir enlace…",
        "Add System Action":"Añadir acción del sistema",
        "Add Shortcut…":    "Añadir atajo…",
        "Add Script…":      "Añadir script…",
        "Add Folder…":      "Añadir carpeta…",
        "Add":              "Añadir",
        "Cancel":           "Cancelar",
        "Create":           "Crear",
        "No items yet":     "Sin elementos",
        "No items":         "Sin elementos",
        "Use the + button to add items.": "Usa el botón + para añadir elementos.",
        "Use the + button or drag files here.": "Usa el botón + o arrastra archivos aquí.",
        "Folder is empty":  "Carpeta vacía",
        "Release to add files": "Suelta para añadir archivos",
        "Search apps…":     "Buscar apps…",
        "Scanning apps…":   "Buscando apps…",
        "Search shortcuts…":"Buscar atajos…",
        "Loading shortcuts…":"Cargando atajos…",
        "No shortcuts found":"No se encontraron atajos",
        "New Folder":       "Nueva carpeta",
        "Folder name":      "Nombre de carpeta",
        "Add Link":         "Añadir enlace",
        "Title (optional)": "Título (opcional)",
        "Title":            "Título",
        "URL":              "URL",
        "Add Shell Script": "Añadir script de shell",
        "Script name":      "Nombre del script",
        "Script":           "Script",
        "Shell script":     "Script de shell",
        "App":              "App",
        "File":             "Archivo",
        "Link":             "Enlace",
        "System":           "Sistema",
        "Shortcut":         "Atajo",
        "Folder":           "Carpeta",
        "Clipboard":        "Portapapeles",
        "Sleep":            "Reposo",
        "Lock Screen":      "Bloquear pantalla",
        "Screen Saver":     "Salvapantallas",
        "Empty Trash":      "Vaciar papelera",
        "Screenshot":       "Captura de pantalla",
        "Context Sets":     "Conjuntos de contexto",
        "App:":             "App:",
        "Choose…":          "Elegir…",
        "No items for this app": "Sin elementos para esta app",
        "Use the + button to add items to this context set.": "Usa el botón + para añadir elementos al conjunto.",
        "Select an app above to create a custom item set\nthat appears when that app is in front.":
            "Selecciona una app para crear un conjunto de elementos\nque aparezca cuando esa app esté en primer plano.",
        "Startup":          "Inicio",
        "Start at Login":   "Iniciar al entrar",
        "Trigger":          "Activador",
        "Mouse shake (hold ⌥ + shake)": "Agitar ratón (mantén ⌥ + agita)",
        "Sensitivity":      "Sensibilidad",
        "Keyboard Shortcut":"Atajo de teclado",
        "Toggle radial menu":"Alternar menú radial",
        "Accessibility Permission Required": "Permiso de accesibilidad requerido",
        "Open System Settings": "Abrir Ajustes del sistema",
        "Later":            "Más tarde",
        "Open Settings to add items": "Abre Ajustes para añadir elementos",
    ],

    .de: [
        "Items":            "Elemente",
        "Context":          "Kontext",
        "General":          "Allgemein",
        "Settings…":        "Einstellungen…",
        "Orbit Settings":   "Orbit-Einstellungen",
        "Orbit Launcher":   "Orbit Starter",
        "Quit Orbit":       "Orbit beenden",
        "Language":         "Sprache",
        "Radial Items":     "Radiale Elemente",
        "Add App…":         "App hinzufügen…",
        "Add File or Folder…": "Datei oder Ordner hinzufügen…",
        "Add Link…":        "Link hinzufügen…",
        "Add System Action":"Systemaktion hinzufügen",
        "Add Shortcut…":    "Kurzbefehl hinzufügen…",
        "Add Script…":      "Skript hinzufügen…",
        "Add Folder…":      "Ordner hinzufügen…",
        "Add":              "Hinzufügen",
        "Cancel":           "Abbrechen",
        "Create":           "Erstellen",
        "No items yet":     "Noch keine Elemente",
        "No items":         "Keine Elemente",
        "Use the + button to add items.": "Verwende +, um Elemente hinzuzufügen.",
        "Use the + button or drag files here.": "Verwende + oder ziehe Dateien hierher.",
        "Folder is empty":  "Ordner ist leer",
        "Release to add files": "Loslassen, um Dateien hinzuzufügen",
        "Search apps…":     "Apps suchen…",
        "Scanning apps…":   "Apps werden gescannt…",
        "Search shortcuts…":"Kurzbefehle suchen…",
        "Loading shortcuts…":"Kurzbefehle werden geladen…",
        "No shortcuts found":"Keine Kurzbefehle gefunden",
        "New Folder":       "Neuer Ordner",
        "Folder name":      "Ordnername",
        "Add Link":         "Link hinzufügen",
        "Title (optional)": "Titel (optional)",
        "Title":            "Titel",
        "URL":              "URL",
        "Add Shell Script": "Shell-Skript hinzufügen",
        "Script name":      "Skriptname",
        "Script":           "Skript",
        "Shell script":     "Shell-Skript",
        "App":              "App",
        "File":             "Datei",
        "Link":             "Link",
        "System":           "System",
        "Shortcut":         "Kurzbefehl",
        "Folder":           "Ordner",
        "Clipboard":        "Zwischenablage",
        "Sleep":            "Ruhezustand",
        "Lock Screen":      "Bildschirm sperren",
        "Screen Saver":     "Bildschirmschoner",
        "Empty Trash":      "Papierkorb leeren",
        "Screenshot":       "Screenshot",
        "Context Sets":     "Kontext-Sets",
        "App:":             "App:",
        "Choose…":          "Auswählen…",
        "No items for this app": "Keine Elemente für diese App",
        "Use the + button to add items to this context set.": "Verwende +, um Elemente zum Kontext-Set hinzuzufügen.",
        "Select an app above to create a custom item set\nthat appears when that app is in front.":
            "Wähle oben eine App, um ein benutzerdefiniertes Set\nzu erstellen, das erscheint, wenn die App aktiv ist.",
        "Startup":          "Start",
        "Start at Login":   "Bei Anmeldung starten",
        "Trigger":          "Auslöser",
        "Mouse shake (hold ⌥ + shake)": "Maus schütteln (⌥ halten + schütteln)",
        "Sensitivity":      "Empfindlichkeit",
        "Keyboard Shortcut":"Tastaturkürzel",
        "Toggle radial menu":"Radialmenü umschalten",
        "Accessibility Permission Required": "Bedienungshilfenberechtigung erforderlich",
        "Open System Settings": "Systemeinstellungen öffnen",
        "Later":            "Später",
        "Open Settings to add items": "Einstellungen öffnen, um Elemente hinzuzufügen",
    ],

    .fr: [
        "Items":            "Éléments",
        "Context":          "Contexte",
        "General":          "Général",
        "Settings…":        "Réglages…",
        "Orbit Settings":   "Réglages Orbit",
        "Orbit Launcher":   "Lanceur Orbit",
        "Quit Orbit":       "Quitter Orbit",
        "Language":         "Langue",
        "Radial Items":     "Éléments radiaux",
        "Add App…":         "Ajouter une app…",
        "Add File or Folder…": "Ajouter un fichier ou dossier…",
        "Add Link…":        "Ajouter un lien…",
        "Add System Action":"Ajouter une action système",
        "Add Shortcut…":    "Ajouter un raccourci…",
        "Add Script…":      "Ajouter un script…",
        "Add Folder…":      "Ajouter un dossier…",
        "Add":              "Ajouter",
        "Cancel":           "Annuler",
        "Create":           "Créer",
        "No items yet":     "Aucun élément",
        "No items":         "Aucun élément",
        "Use the + button to add items.": "Utilisez + pour ajouter des éléments.",
        "Use the + button or drag files here.": "Utilisez + ou faites glisser des fichiers ici.",
        "Folder is empty":  "Dossier vide",
        "Release to add files": "Relâchez pour ajouter des fichiers",
        "Search apps…":     "Rechercher des apps…",
        "Scanning apps…":   "Analyse des apps…",
        "Search shortcuts…":"Rechercher des raccourcis…",
        "Loading shortcuts…":"Chargement des raccourcis…",
        "No shortcuts found":"Aucun raccourci trouvé",
        "New Folder":       "Nouveau dossier",
        "Folder name":      "Nom du dossier",
        "Add Link":         "Ajouter un lien",
        "Title (optional)": "Titre (facultatif)",
        "Title":            "Titre",
        "URL":              "URL",
        "Add Shell Script": "Ajouter un script shell",
        "Script name":      "Nom du script",
        "Script":           "Script",
        "Shell script":     "Script shell",
        "App":              "App",
        "File":             "Fichier",
        "Link":             "Lien",
        "System":           "Système",
        "Shortcut":         "Raccourci",
        "Folder":           "Dossier",
        "Clipboard":        "Presse-papiers",
        "Sleep":            "Veille",
        "Lock Screen":      "Verrouiller l'écran",
        "Screen Saver":     "Économiseur d'écran",
        "Empty Trash":      "Vider la corbeille",
        "Screenshot":       "Capture d'écran",
        "Context Sets":     "Ensembles contextuels",
        "App:":             "App :",
        "Choose…":          "Choisir…",
        "No items for this app": "Aucun élément pour cette app",
        "Use the + button to add items to this context set.": "Utilisez + pour ajouter des éléments à cet ensemble.",
        "Select an app above to create a custom item set\nthat appears when that app is in front.":
            "Sélectionnez une app pour créer un ensemble personnalisé\nqui apparaît quand cette app est au premier plan.",
        "Startup":          "Démarrage",
        "Start at Login":   "Démarrer à l'ouverture de session",
        "Trigger":          "Déclencheur",
        "Mouse shake (hold ⌥ + shake)": "Secouer la souris (maintenir ⌥ + secouer)",
        "Sensitivity":      "Sensibilité",
        "Keyboard Shortcut":"Raccourci clavier",
        "Toggle radial menu":"Afficher/masquer le menu radial",
        "Accessibility Permission Required": "Autorisation d'accessibilité requise",
        "Open System Settings": "Ouvrir les réglages système",
        "Later":            "Plus tard",
        "Open Settings to add items": "Ouvrez les réglages pour ajouter des éléments",
    ],

    .zh: [
        "Items":            "项目",
        "Context":          "情境",
        "General":          "通用",
        "Settings…":        "设置…",
        "Orbit Settings":   "Orbit 设置",
        "Orbit Launcher":   "Orbit 启动器",
        "Quit Orbit":       "退出 Orbit",
        "Language":         "语言",
        "Radial Items":     "环形项目",
        "Add App…":         "添加应用…",
        "Add File or Folder…": "添加文件或文件夹…",
        "Add Link…":        "添加链接…",
        "Add System Action":"添加系统操作",
        "Add Shortcut…":    "添加快捷指令…",
        "Add Script…":      "添加脚本…",
        "Add Folder…":      "添加文件夹…",
        "Add":              "添加",
        "Cancel":           "取消",
        "Create":           "创建",
        "No items yet":     "暂无项目",
        "No items":         "无项目",
        "Use the + button to add items.": "使用 + 按钮添加项目。",
        "Use the + button or drag files here.": "使用 + 按钮或将文件拖放至此。",
        "Folder is empty":  "文件夹为空",
        "Release to add files": "松开以添加文件",
        "Search apps…":     "搜索应用…",
        "Scanning apps…":   "正在扫描应用…",
        "Search shortcuts…":"搜索快捷指令…",
        "Loading shortcuts…":"正在加载快捷指令…",
        "No shortcuts found":"未找到快捷指令",
        "New Folder":       "新建文件夹",
        "Folder name":      "文件夹名称",
        "Add Link":         "添加链接",
        "Title (optional)": "标题（可选）",
        "Title":            "标题",
        "URL":              "网址",
        "Add Shell Script": "添加 Shell 脚本",
        "Script name":      "脚本名称",
        "Script":           "脚本",
        "Shell script":     "Shell 脚本",
        "App":              "应用",
        "File":             "文件",
        "Link":             "链接",
        "System":           "系统",
        "Shortcut":         "快捷指令",
        "Folder":           "文件夹",
        "Clipboard":        "剪贴板",
        "Sleep":            "睡眠",
        "Lock Screen":      "锁定屏幕",
        "Screen Saver":     "屏幕保护程序",
        "Empty Trash":      "清倒废纸篓",
        "Screenshot":       "截图",
        "Context Sets":     "情境集",
        "App:":             "应用：",
        "Choose…":          "选择…",
        "No items for this app": "此应用暂无项目",
        "Use the + button to add items to this context set.": "使用 + 按钮向此情境集添加项目。",
        "Select an app above to create a custom item set\nthat appears when that app is in front.":
            "在上方选择一个应用，创建自定义项目集，\n该集合将在该应用位于前台时显示。",
        "Startup":          "启动",
        "Start at Login":   "登录时启动",
        "Trigger":          "触发方式",
        "Mouse shake (hold ⌥ + shake)": "摇晃鼠标（按住 ⌥ + 摇晃）",
        "Sensitivity":      "灵敏度",
        "Keyboard Shortcut":"键盘快捷键",
        "Toggle radial menu":"切换环形菜单",
        "Accessibility Permission Required": "需要辅助功能权限",
        "Open System Settings": "打开系统设置",
        "Later":            "稍后",
        "Open Settings to add items": "打开设置以添加项目",
    ],

    .ja: [
        "Items":            "項目",
        "Context":          "コンテキスト",
        "General":          "一般",
        "Settings…":        "設定…",
        "Orbit Settings":   "Orbit 設定",
        "Orbit Launcher":   "Orbit ランチャー",
        "Quit Orbit":       "Orbit を終了",
        "Language":         "言語",
        "Radial Items":     "ラジアル項目",
        "Add App…":         "アプリを追加…",
        "Add File or Folder…": "ファイルまたはフォルダを追加…",
        "Add Link…":        "リンクを追加…",
        "Add System Action":"システムアクションを追加",
        "Add Shortcut…":    "ショートカットを追加…",
        "Add Script…":      "スクリプトを追加…",
        "Add Folder…":      "フォルダを追加…",
        "Add":              "追加",
        "Cancel":           "キャンセル",
        "Create":           "作成",
        "No items yet":     "項目がありません",
        "No items":         "項目なし",
        "Use the + button to add items.": "+ ボタンで項目を追加してください。",
        "Use the + button or drag files here.": "+ ボタンを使うか、ファイルをここにドラッグしてください。",
        "Folder is empty":  "フォルダは空です",
        "Release to add files": "ファイルを追加するには離してください",
        "Search apps…":     "アプリを検索…",
        "Scanning apps…":   "アプリをスキャン中…",
        "Search shortcuts…":"ショートカットを検索…",
        "Loading shortcuts…":"ショートカットを読み込み中…",
        "No shortcuts found":"ショートカットが見つかりません",
        "New Folder":       "新規フォルダ",
        "Folder name":      "フォルダ名",
        "Add Link":         "リンクを追加",
        "Title (optional)": "タイトル（任意）",
        "Title":            "タイトル",
        "URL":              "URL",
        "Add Shell Script": "シェルスクリプトを追加",
        "Script name":      "スクリプト名",
        "Script":           "スクリプト",
        "Shell script":     "シェルスクリプト",
        "App":              "アプリ",
        "File":             "ファイル",
        "Link":             "リンク",
        "System":           "システム",
        "Shortcut":         "ショートカット",
        "Folder":           "フォルダ",
        "Clipboard":        "クリップボード",
        "Sleep":            "スリープ",
        "Lock Screen":      "画面をロック",
        "Screen Saver":     "スクリーンセーバ",
        "Empty Trash":      "ゴミ箱を空にする",
        "Screenshot":       "スクリーンショット",
        "Context Sets":     "コンテキストセット",
        "App:":             "アプリ：",
        "Choose…":          "選択…",
        "No items for this app": "このアプリの項目がありません",
        "Use the + button to add items to this context set.": "+ ボタンでこのセットに項目を追加してください。",
        "Select an app above to create a custom item set\nthat appears when that app is in front.":
            "上からアプリを選択して、そのアプリが前面にあるときに\n表示されるカスタム項目セットを作成してください。",
        "Startup":          "起動",
        "Start at Login":   "ログイン時に起動",
        "Trigger":          "トリガー",
        "Mouse shake (hold ⌥ + shake)": "マウスを振る（⌥ を押したまま振る）",
        "Sensitivity":      "感度",
        "Keyboard Shortcut":"キーボードショートカット",
        "Toggle radial menu":"ラジアルメニューを切り替え",
        "Accessibility Permission Required": "アクセシビリティ権限が必要です",
        "Open System Settings": "システム設定を開く",
        "Later":            "後で",
        "Open Settings to add items": "設定を開いて項目を追加",
    ],

    .ru: [
        "Items":            "Элементы",
        "Context":          "Контекст",
        "General":          "Основные",
        "Settings…":        "Настройки…",
        "Orbit Settings":   "Настройки Orbit",
        "Orbit Launcher":   "Orbit Launcher",
        "Quit Orbit":       "Выйти из Orbit",
        "Language":         "Язык",
        "Radial Items":     "Радиальные элементы",
        "Add App…":         "Добавить приложение…",
        "Add File or Folder…": "Добавить файл или папку…",
        "Add Link…":        "Добавить ссылку…",
        "Add System Action":"Добавить системное действие",
        "Add Shortcut…":    "Добавить ярлык…",
        "Add Script…":      "Добавить скрипт…",
        "Add Folder…":      "Добавить папку…",
        "Add":              "Добавить",
        "Cancel":           "Отмена",
        "Create":           "Создать",
        "No items yet":     "Нет элементов",
        "No items":         "Нет элементов",
        "Use the + button to add items.": "Нажмите +, чтобы добавить элементы.",
        "Use the + button or drag files here.": "Нажмите + или перетащите файлы сюда.",
        "Folder is empty":  "Папка пуста",
        "Release to add files": "Отпустите, чтобы добавить файлы",
        "Search apps…":     "Поиск приложений…",
        "Scanning apps…":   "Поиск приложений…",
        "Search shortcuts…":"Поиск ярлыков…",
        "Loading shortcuts…":"Загрузка ярлыков…",
        "No shortcuts found":"Ярлыки не найдены",
        "New Folder":       "Новая папка",
        "Folder name":      "Имя папки",
        "Add Link":         "Добавить ссылку",
        "Title (optional)": "Заголовок (необязательно)",
        "Title":            "Заголовок",
        "URL":              "URL",
        "Add Shell Script": "Добавить скрипт оболочки",
        "Script name":      "Имя скрипта",
        "Script":           "Скрипт",
        "Shell script":     "Скрипт оболочки",
        "App":              "Приложение",
        "File":             "Файл",
        "Link":             "Ссылка",
        "System":           "Система",
        "Shortcut":         "Ярлык",
        "Folder":           "Папка",
        "Clipboard":        "Буфер обмена",
        "Sleep":            "Сон",
        "Lock Screen":      "Заблокировать экран",
        "Screen Saver":     "Заставка",
        "Empty Trash":      "Очистить корзину",
        "Screenshot":       "Снимок экрана",
        "Context Sets":     "Контекстные наборы",
        "App:":             "Приложение:",
        "Choose…":          "Выбрать…",
        "No items for this app": "Нет элементов для этого приложения",
        "Use the + button to add items to this context set.": "Нажмите +, чтобы добавить элементы в этот набор.",
        "Select an app above to create a custom item set\nthat appears when that app is in front.":
            "Выберите приложение выше, чтобы создать набор элементов,\nкоторый появляется, когда это приложение активно.",
        "Startup":          "Запуск",
        "Start at Login":   "Запускать при входе",
        "Trigger":          "Триггер",
        "Mouse shake (hold ⌥ + shake)": "Тряска мыши (удержать ⌥ + трясти)",
        "Sensitivity":      "Чувствительность",
        "Keyboard Shortcut":"Сочетание клавиш",
        "Toggle radial menu":"Переключить радиальное меню",
        "Accessibility Permission Required": "Требуется разрешение специальных возможностей",
        "Open System Settings": "Открыть системные настройки",
        "Later":            "Позже",
        "Open Settings to add items": "Откройте настройки, чтобы добавить элементы",
    ],

    .ko: [
        "Items":            "항목",
        "Context":          "컨텍스트",
        "General":          "일반",
        "Settings…":        "설정…",
        "Orbit Settings":   "Orbit 설정",
        "Orbit Launcher":   "Orbit 런처",
        "Quit Orbit":       "Orbit 종료",
        "Language":         "언어",
        "Radial Items":     "방사형 항목",
        "Add App…":         "앱 추가…",
        "Add File or Folder…": "파일 또는 폴더 추가…",
        "Add Link…":        "링크 추가…",
        "Add System Action":"시스템 동작 추가",
        "Add Shortcut…":    "단축어 추가…",
        "Add Script…":      "스크립트 추가…",
        "Add Folder…":      "폴더 추가…",
        "Add":              "추가",
        "Cancel":           "취소",
        "Create":           "생성",
        "No items yet":     "항목 없음",
        "No items":         "항목 없음",
        "Use the + button to add items.": "+ 버튼을 눌러 항목을 추가하세요.",
        "Use the + button or drag files here.": "+ 버튼을 사용하거나 파일을 여기로 드래그하세요.",
        "Folder is empty":  "폴더가 비어 있습니다",
        "Release to add files": "파일을 추가하려면 놓으세요",
        "Search apps…":     "앱 검색…",
        "Scanning apps…":   "앱 검색 중…",
        "Search shortcuts…":"단축어 검색…",
        "Loading shortcuts…":"단축어 불러오는 중…",
        "No shortcuts found":"단축어를 찾을 수 없음",
        "New Folder":       "새 폴더",
        "Folder name":      "폴더 이름",
        "Add Link":         "링크 추가",
        "Title (optional)": "제목 (선택사항)",
        "Title":            "제목",
        "URL":              "URL",
        "Add Shell Script": "셸 스크립트 추가",
        "Script name":      "스크립트 이름",
        "Script":           "스크립트",
        "Shell script":     "셸 스크립트",
        "App":              "앱",
        "File":             "파일",
        "Link":             "링크",
        "System":           "시스템",
        "Shortcut":         "단축어",
        "Folder":           "폴더",
        "Clipboard":        "클립보드",
        "Sleep":            "잠자기",
        "Lock Screen":      "화면 잠금",
        "Screen Saver":     "화면 보호기",
        "Empty Trash":      "휴지통 비우기",
        "Screenshot":       "스크린샷",
        "Context Sets":     "컨텍스트 세트",
        "App:":             "앱:",
        "Choose…":          "선택…",
        "No items for this app": "이 앱의 항목이 없습니다",
        "Use the + button to add items to this context set.": "+ 버튼으로 이 세트에 항목을 추가하세요.",
        "Select an app above to create a custom item set\nthat appears when that app is in front.":
            "위에서 앱을 선택하여 해당 앱이 전면에 있을 때\n표시되는 사용자 지정 항목 세트를 만드세요.",
        "Startup":          "시작",
        "Start at Login":   "로그인 시 시작",
        "Trigger":          "트리거",
        "Mouse shake (hold ⌥ + shake)": "마우스 흔들기 (⌥ 누른 채 흔들기)",
        "Sensitivity":      "감도",
        "Keyboard Shortcut":"키보드 단축키",
        "Toggle radial menu":"방사형 메뉴 전환",
        "Accessibility Permission Required": "손쉬운 사용 권한 필요",
        "Open System Settings": "시스템 설정 열기",
        "Later":            "나중에",
        "Open Settings to add items": "항목을 추가하려면 설정을 여세요",
    ],
]
